---
- name: install packages for docker
  package:
    name: ['yum-utils','device-mapper-persistent-data','lvm2','device-mapper','device-mapper-event','device-mapper-libs','amazon-linux-extras','device-mapper-event-libs']
    state: present
  when: ansible_facts['distribution'] == 'Amazon'

- name: Enable extras
  raw: yum-config-manager --enable extras
  changed_when: false

- name: Install Docker
  yum: name=docker state=latest
  when: ansible_facts['distribution'] == 'Amazon'

- name: Start/Enable Docker
  service: name=docker state=started enabled=yes
  when: ansible_facts['distribution'] == 'Amazon'

- name: add mysql to docker usergroup
  raw: usermod -aG docker nreddy

- meta: end_play
  when: ansible_facts['distribution'] == 'Amazon'

- name: Enable extras
  raw: yum-config-manager --enable rhel-7-server-rhui-extras-rpms
  when: ansible_facts['distribution'] == 'rhel'

- name: install packages for docker
  package:
    name: ['yum-utils','device-mapper-persistent-data','lvm2','device-mapper','device-mapper-event','device-mapper-libs','device-mapper-event-libs','container-selinux','fuse-overlayfs','slirp4netns']
    state: present
  when: ansible_facts['distribution'] == 'rhel'

- name: Add repository
  raw: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_facts['distribution'] == 'rhel'

- name: setopt
  raw: yum-config-manager --setopt=docker-ce-stable.baseurl=https://download.docker.com/linux/centos/7/x86_64/stable --save
  when: ansible_facts['distribution'] == 'rhel'

- name: Install Docker
  yum: name=docker-ce state=latest
  when: ansible_facts['distribution'] == 'rhel'


- name: Start/Enable Docker
  service: name=docker state=started enabled=yes
  when: ansible_facts['distribution'] == 'rhel'

