---
- name: Create a directory
  file:
    path: /home/nreddy/python
    owner: nreddy
    group: nreddy
    state: directory
    mode: '0755'

- name: Download python scripts
  git:
    repo: https://github.com/rpnarendra/central-dba-ansible.git
    dest: /home/nreddy/python
